# docker-compose.yml
version: '3'
services:
  slidev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3030:3030"
      - "8502:8501"
    # command: python3 run_slidev.py
    tty: true
    user: user
