# docker-compose.yml
version: '3'
services:
  slidev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./slides:/app/slides
    ports:
      - "3030:3030"
    # command: python3 run_slidev.py
    tty: true
    user: user
